version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: examplepassword
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    depends_on:
      - mysql
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wordpress_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    ports:
      - "80:80"
    depends_on:
      - wordpress

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: examplepassword
    ports:
      - "8081:80"
    networks:
      - wordpress_network
    depends_on:
      - mysql

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress_data:
  mysql_data:
