#cloud-config
runcmd:
  - sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd
ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
    root:password
  expire: false
users:
  - name: ubuntu
    gecos: ubuntu
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC866RGM8ZBu6ZzzgBEA/DeWXfXZ80OfcoJasHMBSXJPR4u6JWWjEOTQAsLZIMIYoqehKL2NLYwtnxTA+sP+9uAXNyx2vZaqj/3eR42XBEiGCxhqBqyThqCrOrS6b5LPR/2ZT1y8Mg9s5ODeXIWuXWUV6XI6ixVbCV3Jd5+FWaYqxfkDqjnsfHQnxAkF+K23RV5ttJrwnj55vwUEgiPZKEFpVWpTPQmVKezY20UwlwLoYOXEWV/g5ZLC2E7L3wncalY0zlYZRHaUGrVkLMQp6Wnr1u9gCABlb3n9D8Kn12q9fPzHDHVk5JUcmmskPnN5lGsaezqK8fMtfuaGkbCeW7d root@192.168.122.215
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqiyur0Iqj48ZiKLE2rhZWFGvghmVgDPSVRY9FsRqc3wLHnFKbyw0PQ2qR97xNr01DigZ9skRXAvDE8VzjygmDixPzVyYxoAfM8o7fHrCLlXsVDPIU5UIp9A2FTuv9CA829yXVljz4fhoTl0SgCZPUqvdeScgLIyd8d11sXmDiSfhkg/QYfwNtU5UcoYF3GErjGcxLe/XcuM6LTb0rYn/X45RW0g0337zznjYsPGGkaNYApR1AcRPIL4z3zmXxjALZqzMykzt3zh8+nNDDAZB0B5pCC9bprl6himaVujdeQJej3g3+7ELFq2Vi4YJnWP1UQ2XXUH9ZmVj+sp+hts5t root@192.168.122.62